package ma.streaming.upload.shared.enums;

public enum SeasonEnum {
    SEASON_1,
    SEASON_2,
    SEASON_3,
    SEASON_4,
    SEASON_5,
    SEASON_6,
    SEASON_7,
    SEASON_8,
    SEASON_9,
    SEASON_10,
    SEASON_11,
    SEASON_12,
    SEASON_13,
    SEASON_14,
    SEASON_15,
    SEASON_16,
    SEASON_17,
    SEASON_18,
    SEASON_19,
    SEASON_20,
    SEASON_21,
    SEASON_22,
    SEASON_23,
    SEASON_24,
    SEASON_25,
    SEASON_26,
    SEASON_27,
    SEASON_28,
    SEASON_29,
    SEASON_30,
}
